#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
cat << EOF
We're ready to install the homebrew bundle.

This could take a while.
Are you sure you want to do this now?
EOF
echo ''
read -p "(y/n): " -n1
echo ''
if [[ $REPLY =~ ^[Yy]$ ]] ; then
  brew bundle
else
  echo "Ok. You can always come back and run \`brew bundle\` later."
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
