#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "ready to install the brew bundle"
echo "this could take a while"

read -p "Are you sure you want to do this?
(y/n) " -n 1 -r
if [[$REPLY =~ ^[Yy]$ ]] ; then
  brew bundle
else
  echo "Ok. You can always come back and run \`brew bundle\` later."
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do zsh -c "${installer}" ; done
